"use client"

import { useState } from "react"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { jsPDF } from "jspdf"
import { DisclaimerBanner } from "@/components/DisclaimerBanner"

interface BusinessModel {
  business_idea: string
  business_model_summary: string
  value_proposition: string
  target_customers: string[]
  revenue_streams: string[]
  pricing_strategy: string
  cost_structure: string[]
  key_resources: string[]
  key_activities: string[]
  key_partners: string[]
  channels: string[]
  customer_relationships: string
  unit_economics: string
  scalability: string
  competitive_advantage: string
}

export default function BusinessModelGeneratorPage() {
  const [businessIdea, setBusinessIdea] = useState("")
  const [industry, setIndustry] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [businessModel, setBusinessModel] = useState<BusinessModel | null>(null)
  const [error, setError] = useState<string | null>(null)

  async function generateBusinessModel() {
    if (!businessIdea.trim()) {
      setError("Please describe your business idea")
      return
    }

    setIsGenerating(true)
    setError(null)
    setBusinessModel(null)

    try {
      const response = await fetch("/api/business-model-generator/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          businessIdea: businessIdea.trim(),
          industry: industry.trim() || undefined
        }),
      })

      if (!response.ok) {
        throw new Error("Failed to generate business model")
      }

      const data = await response.json()
      setBusinessModel(data)
    } catch (err: any) {
      setError(err.message || "Failed to generate business model. Please try again.")
    } finally {
      setIsGenerating(false)
    }
  }

  function downloadBusinessModel() {
    if (!businessModel) return

    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const maxWidth = pageWidth - 2 * margin
    let yPosition = margin

    // Helper function to add text with word wrap
    function addText(text: string, fontSize: number, isBold: boolean = false, color: string = "#000000") {
      doc.setFontSize(fontSize)
      doc.setTextColor(color)
      if (isBold) {
        doc.setFont("helvetica", "bold")
      } else {
        doc.setFont("helvetica", "normal")
      }
      
      const lines = doc.splitTextToSize(text, maxWidth)
      lines.forEach((line: string) => {
        if (yPosition > doc.internal.pageSize.getHeight() - 30) {
          doc.addPage()
          yPosition = margin
        }
        doc.text(line, margin, yPosition)
        yPosition += fontSize * 0.4
      })
      yPosition += 5
    }

    function addSection(title: string, content: string | string[]) {
      addText(title, 14, true)
      if (Array.isArray(content)) {
        content.forEach((item) => {
          addText(`• ${item}`, 11)
        })
      } else {
        addText(content, 11)
      }
      yPosition += 5
    }

    // Title
    addText("Business Model Generator", 20, true)
    yPosition += 5

    // Business Idea
    addSection("Business Idea", businessModel.business_idea)
    
    // Business Model Summary
    addSection("Business Model Summary", businessModel.business_model_summary)

    // Value Proposition
    addSection("Value Proposition", businessModel.value_proposition)

    // Target Customers
    addSection("Target Customers", businessModel.target_customers)

    // Revenue Streams
    addSection("Revenue Streams", businessModel.revenue_streams)

    // Pricing Strategy
    addSection("Pricing Strategy", businessModel.pricing_strategy)

    // Cost Structure
    addSection("Cost Structure", businessModel.cost_structure)

    // Key Resources
    addSection("Key Resources", businessModel.key_resources)

    // Key Activities
    addSection("Key Activities", businessModel.key_activities)

    // Key Partners
    addSection("Key Partners", businessModel.key_partners)

    // Channels
    addSection("Channels", businessModel.channels)

    // Customer Relationships
    addSection("Customer Relationships", businessModel.customer_relationships)

    // Unit Economics
    addSection("Unit Economics", businessModel.unit_economics)

    // Scalability
    addSection("Scalability", businessModel.scalability)

    // Competitive Advantage
    addSection("Competitive Advantage", businessModel.competitive_advantage)

    // Footer
    yPosition = doc.internal.pageSize.getHeight() - 15
    doc.setFontSize(10)
    doc.setTextColor("#666666")
    doc.text("Generated by Tool Thinker Business Model Generator", margin, yPosition)

    // Save the PDF
    doc.save(`business-model-${Date.now()}.pdf`)
  }

  return (
    <div className="min-h-screen bg-gray-50 py-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold text-gray-900 mb-4">Business Model Generator</h1>
          <p className="text-xl text-gray-600">
            Generate a comprehensive business model using AI
          </p>
        </div>

        {!businessModel ? (
          <div className="bg-white rounded-lg p-8 shadow-sm">
            <div className="space-y-6">
              <div>
                <label htmlFor="businessIdea" className="block text-sm font-medium text-gray-700 mb-2">
                  Describe Your Business Idea *
                </label>
                <Textarea
                  id="businessIdea"
                  value={businessIdea}
                  onChange={(e) => setBusinessIdea(e.target.value)}
                  placeholder="e.g., A SaaS platform that helps small businesses manage their inventory and track sales in real-time..."
                  rows={6}
                  className="resize-none"
                />
                <p className="mt-2 text-sm text-gray-500">
                  Describe your business concept, product, or service in detail
                </p>
              </div>

              <div>
                <label htmlFor="industry" className="block text-sm font-medium text-gray-700 mb-2">
                  Industry (Optional)
                </label>
                <Input
                  id="industry"
                  value={industry}
                  onChange={(e) => setIndustry(e.target.value)}
                  placeholder="e.g., SaaS, E-commerce, Healthcare, FinTech..."
                />
                <p className="mt-2 text-sm text-gray-500">
                  Specify the industry or sector your business operates in
                </p>
              </div>

              {error && (
                <div className="p-4 bg-red-50 border border-red-200 rounded-lg">
                  <p className="text-red-800 text-sm">{error}</p>
                </div>
              )}

              <Button
                onClick={generateBusinessModel}
                disabled={isGenerating || !businessIdea.trim()}
                className="w-full bg-gray-900 hover:bg-gray-800"
              >
                {isGenerating ? "Generating Business Model..." : "Generate Business Model"}
              </Button>
            </div>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Business Model Header */}
            <div className="bg-white rounded-lg p-8 shadow-sm">
              <div className="flex justify-between items-start mb-6">
                <div>
                  <h2 className="text-3xl font-bold text-gray-900 mb-2">Your Business Model</h2>
                  <p className="text-gray-600">Business Idea: {businessModel.business_idea}</p>
                </div>
                <Button
                  onClick={downloadBusinessModel}
                  className="bg-gray-900 hover:bg-gray-800"
                >
                  Download PDF
                </Button>
              </div>

              <div className="mb-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Business Model Summary</h3>
                <p className="text-gray-600">{businessModel.business_model_summary}</p>
              </div>
            </div>

            {/* Business Model Canvas Sections */}
            <div className="grid md:grid-cols-2 gap-6">
              {/* Value Proposition */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Value Proposition</h3>
                <p className="text-gray-600">{businessModel.value_proposition}</p>
              </div>

              {/* Target Customers */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Target Customers</h3>
                <ul className="space-y-2">
                  {businessModel.target_customers.map((customer, idx) => (
                    <li key={idx} className="text-gray-600 flex items-start">
                      <span className="mr-2">•</span>
                      <span>{customer}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Revenue Streams */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Revenue Streams</h3>
                <ul className="space-y-2">
                  {businessModel.revenue_streams.map((stream, idx) => (
                    <li key={idx} className="text-gray-600 flex items-start">
                      <span className="mr-2">•</span>
                      <span>{stream}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Pricing Strategy */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Pricing Strategy</h3>
                <p className="text-gray-600">{businessModel.pricing_strategy}</p>
              </div>

              {/* Cost Structure */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Cost Structure</h3>
                <ul className="space-y-2">
                  {businessModel.cost_structure.map((cost, idx) => (
                    <li key={idx} className="text-gray-600 flex items-start">
                      <span className="mr-2">•</span>
                      <span>{cost}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Key Resources */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Key Resources</h3>
                <ul className="space-y-2">
                  {businessModel.key_resources.map((resource, idx) => (
                    <li key={idx} className="text-gray-600 flex items-start">
                      <span className="mr-2">•</span>
                      <span>{resource}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Key Activities */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Key Activities</h3>
                <ul className="space-y-2">
                  {businessModel.key_activities.map((activity, idx) => (
                    <li key={idx} className="text-gray-600 flex items-start">
                      <span className="mr-2">•</span>
                      <span>{activity}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Key Partners */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Key Partners</h3>
                <ul className="space-y-2">
                  {businessModel.key_partners.map((partner, idx) => (
                    <li key={idx} className="text-gray-600 flex items-start">
                      <span className="mr-2">•</span>
                      <span>{partner}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Channels */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Channels</h3>
                <ul className="space-y-2">
                  {businessModel.channels.map((channel, idx) => (
                    <li key={idx} className="text-gray-600 flex items-start">
                      <span className="mr-2">•</span>
                      <span>{channel}</span>
                    </li>
                  ))}
                </ul>
              </div>

              {/* Customer Relationships */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Customer Relationships</h3>
                <p className="text-gray-600">{businessModel.customer_relationships}</p>
              </div>

              {/* Unit Economics */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Unit Economics</h3>
                <p className="text-gray-600">{businessModel.unit_economics}</p>
              </div>

              {/* Scalability */}
              <div className="bg-white rounded-lg p-6 shadow-sm">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Scalability</h3>
                <p className="text-gray-600">{businessModel.scalability}</p>
              </div>

              {/* Competitive Advantage */}
              <div className="bg-white rounded-lg p-6 shadow-sm md:col-span-2">
                <h3 className="text-xl font-bold text-gray-900 mb-3">Competitive Advantage</h3>
                <p className="text-gray-600">{businessModel.competitive_advantage}</p>
              </div>
            </div>

            {/* Actions */}
            <div className="bg-white rounded-lg p-6 shadow-sm">
              <div className="flex gap-4">
                <Button
                  onClick={() => {
                    setBusinessModel(null)
                    setBusinessIdea("")
                    setIndustry("")
                  }}
                  variant="outline"
                  className="flex-1"
                >
                  Generate New Model
                </Button>
                <Button
                  onClick={downloadBusinessModel}
                  className="flex-1 bg-gray-900 hover:bg-gray-800"
                >
                  Download PDF
                </Button>
              </div>
            </div>

            <DisclaimerBanner className="mt-8" />
          </div>
        )}
      </div>
    </div>
  )
}
