"use client"

import { useState } from "react"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { jsPDF } from "jspdf"
import { DisclaimerBanner } from "@/components/DisclaimerBanner"
import { ShareButton } from "@/components/ShareButton"
import { Compass } from "lucide-react"

interface RoadmapStep {
  step: number
  framework: string
  description: string
  why: string
  outcome: string
}

interface Roadmap {
  goal: string
  summary: string
  steps: RoadmapStep[]
  estimatedTime: string
  keyFrameworks: string[]
}

export default function FrameworkNavigatorPage() {
  const [businessGoal, setBusinessGoal] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null)
  const [error, setError] = useState<string | null>(null)

  async function generateRoadmap() {
    if (!businessGoal.trim()) {
      setError("Please enter your business goal")
      return
    }

    setIsGenerating(true)
    setError(null)
    setRoadmap(null)

    try {
      const response = await fetch("/api/framework-navigator/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ goal: businessGoal }),
      })

      if (!response.ok) {
        throw new Error("Failed to generate roadmap")
      }

      const data = await response.json()
      setRoadmap(data)
    } catch (err: any) {
      setError(err.message || "Failed to generate roadmap. Please try again.")
    } finally {
      setIsGenerating(false)
    }
  }

  function downloadRoadmap() {
    if (!roadmap) return

    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const maxWidth = pageWidth - 2 * margin
    let yPosition = margin

    // Helper function to add text with word wrap
    function addText(text: string, fontSize: number, isBold: boolean = false, color: string = "#000000") {
      doc.setFontSize(fontSize)
      doc.setTextColor(color)
      if (isBold) {
        doc.setFont("helvetica", "bold")
      } else {
        doc.setFont("helvetica", "normal")
      }
      
      const lines = doc.splitTextToSize(text, maxWidth)
      lines.forEach((line: string) => {
        if (yPosition > doc.internal.pageSize.getHeight() - 30) {
          doc.addPage()
          yPosition = margin
        }
        doc.text(line, margin, yPosition)
        yPosition += fontSize * 0.4
      })
      yPosition += 5
    }

    // Title
    addText("Framework Navigator Roadmap", 20, true)
    yPosition += 5

    // Business Goal
    addText("Business Goal", 14, true)
    addText(roadmap.goal, 12)
    yPosition += 5

    // Summary
    addText("Summary", 14, true)
    addText(roadmap.summary, 12)
    yPosition += 5

    // Estimated Time and Key Frameworks
    addText("Estimated Time", 14, true)
    addText(roadmap.estimatedTime, 12)
    yPosition += 5

    addText("Key Frameworks", 14, true)
    addText(roadmap.keyFrameworks.join(", "), 12)
    yPosition += 10

    // Roadmap Steps
    addText("Roadmap Steps", 16, true)
    yPosition += 5

    roadmap.steps.forEach((step, idx) => {
      if (idx > 0) {
        yPosition += 5
      }

      // Step number and framework name
      addText(`Step ${step.step}: ${step.framework}`, 14, true)
      yPosition += 3

      // Description
      addText("Description:", 12, true)
      addText(step.description, 11)
      yPosition += 3

      // Why
      addText("Why this framework:", 12, true)
      addText(step.why, 11)
      yPosition += 3

      // Outcome
      addText("Expected Outcome:", 12, true)
      addText(step.outcome, 11)
      yPosition += 8
    })

    // Footer
    yPosition = doc.internal.pageSize.getHeight() - 15
    doc.setFontSize(10)
    doc.setTextColor("#666666")
    doc.text("Generated by Tool Thinker Framework Navigator", margin, yPosition)

    // Save the PDF
    doc.save(`framework-roadmap-${Date.now()}.pdf`)
  }

  return (
    <div className="min-h-screen bg-gradient-to-b from-gray-50 via-white to-gray-50 py-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Enhanced Hero Section */}
        <div className="text-center mb-16 relative">
          <div className="absolute top-0 right-0">
            <ShareButton toolName="Framework Navigator" toolId="framework-navigator" />
          </div>
          <div className="inline-block mb-6">
            <div className="w-20 h-20 rounded-2xl bg-gradient-to-br from-gray-900 to-gray-700 flex items-center justify-center shadow-lg mx-auto">
              <Compass className="w-10 h-10 text-white" />
            </div>
          </div>
          <h1 className="text-5xl md:text-6xl font-bold text-gray-900 mb-6 tracking-tight">
            Framework Navigator
          </h1>
          <p className="text-xl text-gray-600 max-w-2xl mx-auto leading-relaxed">
            Start your journey by entering your goal below
          </p>
          <div className="w-24 h-1 bg-gradient-to-r from-gray-900 to-gray-700 mx-auto mt-6 rounded-full"></div>
        </div>

        {!roadmap ? (
          <div className="bg-white rounded-2xl p-10 shadow-xl border-2 border-gray-100">
            <div className="mb-8">
              <label htmlFor="goal" className="block text-sm font-semibold text-gray-900 mb-3">
                What is your business goal?
              </label>
              <Textarea
                id="goal"
                value={businessGoal}
                onChange={(e) => setBusinessGoal(e.target.value)}
                placeholder="e.g., Launch a SaaS product for small businesses, Validate my startup idea, Scale my existing business..."
                rows={6}
                className="resize-none border-2 border-gray-200 focus:border-gray-900 focus:ring-2 focus:ring-gray-900 rounded-xl"
              />
              <p className="mt-2 text-sm text-gray-500">
                Describe what you want to achieve with your business or startup
              </p>
            </div>

            {error && (
              <div className="mb-6 p-4 bg-red-50 border-2 border-red-200 rounded-xl">
                <p className="text-red-800 text-sm font-medium">{error}</p>
              </div>
            )}

            <div className="flex gap-4">
              <Button
                onClick={generateRoadmap}
                disabled={isGenerating || !businessGoal.trim()}
                className="flex-1 bg-gradient-to-r from-gray-900 to-gray-800 hover:from-gray-800 hover:to-gray-700 text-white py-6 text-lg font-semibold rounded-xl shadow-lg hover:shadow-xl transition-all duration-200 transform hover:scale-[1.02]"
              >
                {isGenerating ? (
                  <span className="flex items-center justify-center gap-2">
                    <svg className="animate-spin h-5 w-5" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Generating Roadmap...
                  </span>
                ) : (
                  "Generate Roadmap"
                )}
              </Button>
            </div>
          </div>
        ) : (
          <div className="space-y-8">
            {/* Roadmap Header */}
            <div className="bg-gradient-to-br from-gray-900 to-gray-800 rounded-2xl p-8 shadow-xl text-white">
              <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-6">
                <div>
                  <h2 className="text-3xl font-bold mb-2">Your Framework Roadmap</h2>
                  <p className="text-gray-300 text-lg">Goal: {roadmap.goal}</p>
                </div>
                <div className="flex flex-col sm:flex-row gap-3">
                  <ShareButton toolName="Framework Navigator" toolId="framework-navigator" className="bg-white text-gray-900 hover:bg-gray-100 font-semibold px-6 py-3 rounded-xl shadow-lg hover:shadow-xl transition-all" />
                  <Button
                    onClick={downloadRoadmap}
                    className="bg-white text-gray-900 hover:bg-gray-100 font-semibold px-6 py-3 rounded-xl shadow-lg hover:shadow-xl transition-all"
                  >
                    📥 Download Roadmap
                  </Button>
                </div>
              </div>

              <div className="mb-6 bg-white/10 rounded-xl p-6 backdrop-blur-sm">
                <h3 className="text-lg font-bold text-white mb-3">Summary</h3>
                <p className="text-gray-100 leading-relaxed">{roadmap.summary}</p>
              </div>

              <div className="grid md:grid-cols-2 gap-4">
                <div className="bg-white/10 rounded-xl p-5 backdrop-blur-sm">
                  <h3 className="text-sm font-bold text-gray-200 mb-2 uppercase tracking-wide">Estimated Time</h3>
                  <p className="text-white text-lg font-semibold">{roadmap.estimatedTime}</p>
                </div>
                <div className="bg-white/10 rounded-xl p-5 backdrop-blur-sm">
                  <h3 className="text-sm font-bold text-gray-200 mb-2 uppercase tracking-wide">Key Frameworks</h3>
                  <div className="flex flex-wrap gap-2">
                    {roadmap.keyFrameworks.map((framework, idx) => (
                      <span
                        key={idx}
                        className="px-3 py-1.5 bg-white/20 text-white rounded-lg text-sm font-medium border border-white/30"
                      >
                        {framework}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Roadmap Steps */}
            <div className="space-y-6">
              {roadmap.steps.map((step, idx) => (
                <div key={idx} className="bg-white rounded-2xl p-8 shadow-lg border-2 border-gray-100 hover:shadow-xl transition-all">
                  <div className="flex items-start gap-6">
                    <div className="flex-shrink-0 w-14 h-14 bg-gradient-to-br from-gray-900 to-gray-700 text-white rounded-xl flex items-center justify-center font-bold text-lg shadow-lg">
                      {step.step}
                    </div>
                    <div className="flex-1">
                      <h3 className="text-xl font-bold text-gray-900 mb-2">{step.framework}</h3>
                      <p className="text-gray-600 mb-4">{step.description}</p>
                      <div className="space-y-2">
                        <div>
                          <span className="text-sm font-semibold text-gray-700">Why this framework: </span>
                          <span className="text-sm text-gray-600">{step.why}</span>
                        </div>
                        <div>
                          <span className="text-sm font-semibold text-gray-700">Expected Outcome: </span>
                          <span className="text-sm text-gray-600">{step.outcome}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Actions */}
            <div className="bg-white rounded-lg p-6 shadow-sm">
              <div className="flex gap-4">
                <Button
                  onClick={() => {
                    setRoadmap(null)
                    setBusinessGoal("")
                  }}
                  variant="outline"
                  className="flex-1"
                >
                  Start New Roadmap
                </Button>
                <Button
                  onClick={downloadRoadmap}
                  className="flex-1 bg-gray-900 hover:bg-gray-800"
                >
                  Download Roadmap
                </Button>
              </div>
            </div>

            <DisclaimerBanner className="mt-8" />
          </div>
        )}
      </div>
    </div>
  )
}
