"use client"

import { useState } from "react"
import { Textarea } from "@/components/ui/textarea"
import { Button } from "@/components/ui/button"
import { jsPDF } from "jspdf"

interface RoadmapStep {
  step: number
  framework: string
  description: string
  why: string
  outcome: string
}

interface Roadmap {
  goal: string
  summary: string
  steps: RoadmapStep[]
  estimatedTime: string
  keyFrameworks: string[]
}

export default function FrameworkNavigatorPage() {
  const [businessGoal, setBusinessGoal] = useState("")
  const [isGenerating, setIsGenerating] = useState(false)
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null)
  const [error, setError] = useState<string | null>(null)

  async function generateRoadmap() {
    if (!businessGoal.trim()) {
      setError("Please enter your business goal")
      return
    }

    setIsGenerating(true)
    setError(null)
    setRoadmap(null)

    try {
      const response = await fetch("/api/framework-navigator/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ goal: businessGoal }),
      })

      if (!response.ok) {
        throw new Error("Failed to generate roadmap")
      }

      const data = await response.json()
      setRoadmap(data)
    } catch (err: any) {
      setError(err.message || "Failed to generate roadmap. Please try again.")
    } finally {
      setIsGenerating(false)
    }
  }

  function downloadRoadmap() {
    if (!roadmap) return

    const doc = new jsPDF()
    const pageWidth = doc.internal.pageSize.getWidth()
    const margin = 20
    const maxWidth = pageWidth - 2 * margin
    let yPosition = margin

    // Helper function to add text with word wrap
    function addText(text: string, fontSize: number, isBold: boolean = false, color: string = "#000000") {
      doc.setFontSize(fontSize)
      doc.setTextColor(color)
      if (isBold) {
        doc.setFont("helvetica", "bold")
      } else {
        doc.setFont("helvetica", "normal")
      }
      
      const lines = doc.splitTextToSize(text, maxWidth)
      lines.forEach((line: string) => {
        if (yPosition > doc.internal.pageSize.getHeight() - 30) {
          doc.addPage()
          yPosition = margin
        }
        doc.text(line, margin, yPosition)
        yPosition += fontSize * 0.4
      })
      yPosition += 5
    }

    // Title
    addText("Framework Navigator Roadmap", 20, true)
    yPosition += 5

    // Business Goal
    addText("Business Goal", 14, true)
    addText(roadmap.goal, 12)
    yPosition += 5

    // Summary
    addText("Summary", 14, true)
    addText(roadmap.summary, 12)
    yPosition += 5

    // Estimated Time and Key Frameworks
    addText("Estimated Time", 14, true)
    addText(roadmap.estimatedTime, 12)
    yPosition += 5

    addText("Key Frameworks", 14, true)
    addText(roadmap.keyFrameworks.join(", "), 12)
    yPosition += 10

    // Roadmap Steps
    addText("Roadmap Steps", 16, true)
    yPosition += 5

    roadmap.steps.forEach((step, idx) => {
      if (idx > 0) {
        yPosition += 5
      }

      // Step number and framework name
      addText(`Step ${step.step}: ${step.framework}`, 14, true)
      yPosition += 3

      // Description
      addText("Description:", 12, true)
      addText(step.description, 11)
      yPosition += 3

      // Why
      addText("Why this framework:", 12, true)
      addText(step.why, 11)
      yPosition += 3

      // Outcome
      addText("Expected Outcome:", 12, true)
      addText(step.outcome, 11)
      yPosition += 8
    })

    // Footer
    yPosition = doc.internal.pageSize.getHeight() - 15
    doc.setFontSize(10)
    doc.setTextColor("#666666")
    doc.text("Generated by Tool Thinker Framework Navigator", margin, yPosition)

    // Save the PDF
    doc.save(`framework-roadmap-${Date.now()}.pdf`)
  }

  return (
    <div className="min-h-screen bg-gray-50 py-16">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-12">
          <h1 className="text-5xl font-bold text-gray-900 mb-4">Framework Navigator</h1>
          <p className="text-xl text-gray-600">
            Start your journey by entering your goal below
          </p>
        </div>

        {!roadmap ? (
          <div className="bg-white rounded-lg p-8 shadow-sm">
            <div className="mb-6">
              <label htmlFor="goal" className="block text-sm font-medium text-gray-700 mb-2">
                What is your business goal?
              </label>
              <Textarea
                id="goal"
                value={businessGoal}
                onChange={(e) => setBusinessGoal(e.target.value)}
                placeholder="e.g., Launch a SaaS product for small businesses, Validate my startup idea, Scale my existing business..."
                rows={6}
                className="resize-none"
              />
              <p className="mt-2 text-sm text-gray-500">
                Describe what you want to achieve with your business or startup
              </p>
            </div>

            {error && (
              <div className="mb-6 p-4 bg-red-50 border border-red-200 rounded-lg">
                <p className="text-red-800 text-sm">{error}</p>
              </div>
            )}

            <div className="flex gap-4">
              <Button
                onClick={generateRoadmap}
                disabled={isGenerating || !businessGoal.trim()}
                className="flex-1 bg-gray-900 hover:bg-gray-800"
              >
                {isGenerating ? "Generating Roadmap..." : "Generate Roadmap"}
              </Button>
            </div>
          </div>
        ) : (
          <div className="space-y-6">
            {/* Roadmap Header */}
            <div className="bg-white rounded-lg p-8 shadow-sm">
              <div className="flex justify-between items-start mb-6">
                <div>
                  <h2 className="text-3xl font-bold text-gray-900 mb-2">Your Framework Roadmap</h2>
                  <p className="text-gray-600">Goal: {roadmap.goal}</p>
                </div>
                <Button
                  onClick={downloadRoadmap}
                  className="bg-gray-900 hover:bg-gray-800"
                >
                  Download Roadmap
                </Button>
              </div>

              <div className="mb-6">
                <h3 className="text-lg font-semibold text-gray-900 mb-2">Summary</h3>
                <p className="text-gray-600">{roadmap.summary}</p>
              </div>

              <div className="grid md:grid-cols-2 gap-4 mb-6">
                <div>
                  <h3 className="text-sm font-semibold text-gray-700 mb-1">Estimated Time</h3>
                  <p className="text-gray-900">{roadmap.estimatedTime}</p>
                </div>
                <div>
                  <h3 className="text-sm font-semibold text-gray-700 mb-1">Key Frameworks</h3>
                  <div className="flex flex-wrap gap-2">
                    {roadmap.keyFrameworks.map((framework, idx) => (
                      <span
                        key={idx}
                        className="px-3 py-1 bg-gray-100 text-gray-700 rounded text-sm"
                      >
                        {framework}
                      </span>
                    ))}
                  </div>
                </div>
              </div>
            </div>

            {/* Roadmap Steps */}
            <div className="space-y-4">
              {roadmap.steps.map((step, idx) => (
                <div key={idx} className="bg-white rounded-lg p-6 shadow-sm border-l-4 border-gray-900">
                  <div className="flex items-start gap-4">
                    <div className="flex-shrink-0 w-10 h-10 bg-gray-900 text-white rounded-full flex items-center justify-center font-bold">
                      {step.step}
                    </div>
                    <div className="flex-1">
                      <h3 className="text-xl font-bold text-gray-900 mb-2">{step.framework}</h3>
                      <p className="text-gray-600 mb-4">{step.description}</p>
                      <div className="space-y-2">
                        <div>
                          <span className="text-sm font-semibold text-gray-700">Why this framework: </span>
                          <span className="text-sm text-gray-600">{step.why}</span>
                        </div>
                        <div>
                          <span className="text-sm font-semibold text-gray-700">Expected Outcome: </span>
                          <span className="text-sm text-gray-600">{step.outcome}</span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            {/* Actions */}
            <div className="bg-white rounded-lg p-6 shadow-sm">
              <div className="flex gap-4">
                <Button
                  onClick={() => {
                    setRoadmap(null)
                    setBusinessGoal("")
                  }}
                  variant="outline"
                  className="flex-1"
                >
                  Start New Roadmap
                </Button>
                <Button
                  onClick={downloadRoadmap}
                  className="flex-1 bg-gray-900 hover:bg-gray-800"
                >
                  Download Roadmap
                </Button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
